### PR TITLE
Test against expectation

### PR DESCRIPTION
**Pull request by EpicWink**
Test against the provided expectation in toml-test.

I created a recursive assertion function for comparison rather than using toml-test's Go app as the recursion implementation was going to be needed anyway, and this way we don't have to set up a Go environment, and write a command-line app which handles JSON and TOML from stdin to stdout.

### CODE REVIEW

**Comment by bobfang1992** [comment]
This is a good change and something I wanted to do :) Looks promising. Let me know when you are ready for review etc. Thanks!

**Comment by EpicWink** [comment]
@bobfang1992 Ready

**Comment by bobfang1992** [comment]
LGTM, could you rebase and I will merge? Thanks!

**Comment by EpicWink** [comment]
@bobfang1992 That's been done

**Pull request merged**
