### PR TITLE
Mark package as typed

### PR DESCRIPTION
**Pull request by Viicos**
So that mypy can pick it up

### CODE REVIEW

**Comment by bobfang1992** [comment]
@Viicos  It only have two functions and I highly encourage to create a PR yourself. I am happy to review but I dont have much time to do this myeself atm.

**Comment by Viicos** [comment]
@bobfang1992 this is actually a PR 😅

**Comment by bobfang1992** [comment]
@Viicos my bad :) since you are already adding this file why not add some actual content?

**Comment by bobfang1992** [comment]
Hi sorry for being so late but this is now released in new version 1.0.13 :) Thanks for adding this

**Pull request merged**
