### PR TITLE
updating toml++ to v3

### PR DESCRIPTION
**Pull request by marzer**
@bobfang1992 please don't merge this in just yet as toml++ v3 is still in development. I'm just using this PR as a hook into your CI to make sure things work OK. I'll update the PR when I release v3 properly ^_^

### CODE REVIEW

**Comment by marzer** [comment]
Damn, your CI kicked my ass, lol.

**Comment by bobfang1992** [comment]
@marzer yeah we are supporting quite a few platforms so haha sometimes people do get caught with it.

**Comment by bobfang1992** [comment]
@marzer And congratulation on beating rtoml :) wondering if you did some optimisation specifically on v3 side or it is simply using `std::move` made it fast. But great showing C++ is still faster than Rust.

**Comment by marzer** [comment]
Thanks! I did a lot of work in the parser to eliminate a number of unnecessary string allocations, and added a SIMD fast-path to the unicode decoder.

**Comment by marzer** [comment]
@bobfang1992 I released toml++ v3 earlier and have updated this PR accordingly. I'll let you do the honours ^_^

**Comment by bobfang1992** [comment]
@marzer  Hi, congratulations! Quite an achievement. I will merge this now!

**Pull request merged**
