### PR TITLE
update toml++ to v3.1.0

### PR DESCRIPTION
**Pull request by marzer**
also:
- update benchmark script to handle parse failures
- update benchmark data to better stress-test parsers
- added PEP 680 awareness to the benchmark script (`tomllib`)
- made the toml++ submodule shallow by default
- minor perf tweaks

### CODE REVIEW

**Comment by marzer** [comment]
@pwwang Note that this PR replaces the benchmark data.toml with a much larger and more complex one, which also has some TOML v1.0.0 features. You might need to update toml-bench to take this into account - `sdispater/tomlkit` takes an eternity go get through it, and `uiri/toml` fails completely.

**Comment by marzer** [comment]
Actually, don't merge this yet. Just realized there might be a way I can make the encoding/decoding bits faster.

**Comment by marzer** [comment]
Well, no huge perf gains. Oh well. On the plus side, I was able to simplify some things using v3.1.0's `for_each()` ^_^

**Review by bobfang1992 — APPROVED** [review]

**Comment by bobfang1992** [comment]
Hi, thanks! feel free to merge it!

**Pull request merged**
