### PR TITLE
Add optional encoding parameter to load and dump functions

### PR DESCRIPTION
**Pull request by Backist**
An optional ``encoding`` parameter has been added to the ``dump`` and ``load`` functions to provide more flexibility in specifying encoding, rather than always using the system default.

### CODE REVIEW

**Comment by Backist** [comment]
After several hours of struggling with my machine with a GIT Bash problem, I present the final PR including the ``encoding`` parameter to the dump and load functions. Although I had initially set ``utf-8`` as the default for enconding, it seemed that some tests were using different encodings, so I considered leaving it at None and letting the user set the required encoding.

**Comment by Backist** [comment]
PS: Apologies for the number of failed or cancelled PRs. Several of them were not correct or had late commits due to the problem with my GIT Bash that I mentioned.

**Comment by Backist** [comment]
@bobfang1992 Awaiting review. Everything should now be in order.

**Review by bobfang1992 — APPROVED** [review]

**Comment by bobfang1992** [comment]
Thanks, will merge if all CI passes

**Pull request merged**
