### PR TITLE
Build and upload source dists (fixes #47)

### LINKED ISSUE #47: upload a source dist to PyPI
Currently only pre-built wheels are uploaded on pypi, meaning unsupported platforms cannot install this package at all even if they can compile it. Please upload a source dist (setup.py sdist; twine upload dist/*) because as it stands I cannot install this on my ARM phone.

### PR DESCRIPTION
**Pull request by ioistired**
Updates the GitHub Actions: adds a job to build and upload an sdist artifact.

fixes #47

### CODE REVIEW

**Comment by ioistired** [comment]
Hm… this build failure is unrelated to my changes. The job I added succeeded, in fact.

**Comment by bobfang1992** [comment]
ok I can take a look during the weekend probably.

**Comment by bobfang1992** [comment]
Seems Py3.5 is deprecated and the issue is somehow related to Py3.5. Do you mind helping me to change the CIBW_SKIP variable to ignore build for Py3.5? Thanks!

**Comment by bobfang1992** [comment]
From
```
       CIBW_SKIP: cp27-* pp* *-win32
```
change to 
```
        CIBW_SKIP: cp27-* pp* *-win32 cp35-*
```

**Comment by bobfang1992** [comment]
Hi I fixed this can you rebase and then you should be fine?

**Comment by bobfang1992** [comment]
my MR https://github.com/bobfang1992/pytomlpp/pull/53

**Comment by bobfang1992** [comment]
ping @ioistired

**Comment by ioistired** [comment]
Rebased

**Review by marzer — CHANGES_REQUESTED** [review]
@ioistired Seems you need to pull the toml++ submodule too; this PR would rewind toml++ from 2.4.0 to 2.3.0.

(I updated it in a separate PR after you forked this repo)

**Comment by ioistired** [comment]
That's odd, I just rebased on top of master, which includes commit 970d1bcee535cc7f34f04b513c64e379e976d6fa which upgrades toml++

**Comment by ioistired** [comment]
What would you like me to do?

**Comment by marzer** [comment]
@ioistired I believe this should be sufficient:

```sh
cd third_party/tomlplusplus && git checkout d962c6ccc1241a3906642c071d27b11a031471b4
```

**Comment by ioistired** [comment]
How's that?

**Review by marzer — APPROVED** [review]

**Comment by marzer** [comment]
Yup, looking good.

**Comment by ioistired** [comment]
> What controls the behavior?

Whether there's a binary distribution available for your platform. Pip prefers binary distributions by default. If there's no wheel for your platform it will download and try to compile the source.

**Comment by bobfang1992** [comment]
> > What controls the behavior?
> 
> Whether there's a binary distribution available for your platform. Pip prefers binary distributions by default. If there's no wheel for your platform it will download and try to compile the source.

Cool, this one needs a fairly new compiler toochain so I am not sure how many python guys will have that installed. But anyway this is a good addition and I will merge it now.

**Pull request merged**
